# Numpy
## 1. ndarray

ndarray는 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열이다.
ndarra의 모든 원소는 같은 자료형이어야 한다.

-Shape: 모든 배열은 각 차원의 크기를 알려주는 튜플. 차원의 구조 (행*열)형태로 표시

-dtype: 배열에 저장된 자료를 알려주는 객체

### 1.1 배열 생성함수

np.array(): 순서가 있는 객체(주로 리스트)로 넘겨받아 데이터가 들어있는 새로운 NumPy 배열 생성

다차원 배열 ~ 일종의 매트릭스

np.asarray: 입력데이터를 ndarray로 변환

np.arange: range 함수와 유사하나 ndarray를 반환

np.ones: 전달인자로 전달한 dtype과 모양(행,렬)으로 배열을 생성하고 모든 내용을 1로 초기화하여 ndarray를 반환

np.zeros: ones와 같으나 초기값이 0

np.empty: ones와 zeros와 비슷하나 값을 초기화 하지는 않는다

### 1.2 배열의 데이터 타입

np.array(list, dtype = np.float64)
데이터 타입 명시 가능

array.dtype
해당 ndarray의 데이터 타입 확인

#### Numpy의 자료형들
float(부동소수점)
complex(복소수)
int(정수)
bool(불리언)
string(문자열)
object(파이썬 객체)

### 1.3 배열과 스칼라 연산

In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [4]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

### 1.4 NumPy 배열 색인과 슬라이싱

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[5]

5

In [8]:
arr[5:8]

array([5, 6, 7])

In [9]:
arr[5:8] = 100

In [10]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [11]:
li = list(range(10))

In [12]:
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
li[5:8]

[5, 6, 7]

* li[5:8] = 100 리스트 형태는 다음과 같이 할당 안돼

for 문을 통해 100을 할당 시켜야 함

### 1.5 불리언 색인

In [14]:
names = np.array(['John', 'Tom',' James', 'Sally'])

In [15]:
names

array(['John', 'Tom', ' James', 'Sally'], dtype='<U6')

In [16]:
names == 'John'

array([ True, False, False, False])

In [17]:
data = np.random.randn(4,4)

In [18]:
data

array([[-1.78019169, -0.14389505, -1.32440306,  0.89855124],
       [-1.19406731, -1.65240051,  1.65733752,  0.15242692],
       [-0.33595407, -0.21885827, -0.8815867 ,  2.08803559],
       [-1.69443268, -2.20870802, -2.48001313, -1.60769163]])

In [19]:
data[names=='John']

array([[-1.78019169, -0.14389505, -1.32440306,  0.89855124]])

In [20]:
data[data<0] = 0

In [21]:
data

array([[0.        , 0.        , 0.        , 0.89855124],
       [0.        , 0.        , 1.65733752, 0.15242692],
       [0.        , 0.        , 0.        , 2.08803559],
       [0.        , 0.        , 0.        , 0.        ]])

## 2. 유니버셜 함수 unfunc

unfunc(유니버셜 함수):

ndarray에 있는 데이터 원소 별로 연산을 수행하는 함수

In [22]:
np.sqrt(np.arange(10))

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

단일 배열에 사용하는 함수 (e.g., abs,fabs,sqrt,Exp,isnan...)

서로 다른 배열 간에 사용하는 함수 (e.g., add, maximum, mod ...)

## 3. 배열을 사용한 데이터 처리

### 3.1 조건절 표현

np.where(조건,x,y)

조건이 참이면 'x', 거짓이면 'y' 의 원소로 하는 벡터를 반환

In [23]:
xarr = np.array([1,1,1,1,1])
yarr = np.array([0,0,0,0,0])
cond = np.array([True, False, True, True, False])

                 

In [24]:
result = np.where(cond,xarr,yarr)

In [25]:
result

array([1, 0, 1, 1, 0])

### 3.2 통계 Method

In [26]:
a = np.array([[1,3,4,5,5],[2,5,2,7,10]])

In [27]:
np.sum(a)

44

In [28]:
np.max(a, axis = 1)

array([ 5, 10])

In [29]:
np.max(a, axis = 0)

array([ 2,  5,  4,  7, 10])

### 3.3 불리언 Method
### 3.4 정렬 Method
### 3.5 집합 함수
## 4. 배열의 파일 입출력
## 5. 선형대수


## 6. 난수 생성

### 시드 설정하기

In [30]:
np.random.seed(0)

컴퓨터에서 발생하는 무작위 수는 사실 엄격한 의미의 Random이라고 할 수 없다.
어떤 특정한 시작 숫자를 정해주면 컴퓨터가 난수처럼 보이는 수열을 생성할 뿐이다. 이런 시작 숫자를 seed라고 하는데, 이 seed값을 통해 난수 1개를 생성해내고 그 다음 숫자는 첫번째 난수를 통해 난수를 생성한다. 시드는 보통 현재 시각 등을 이용하여 정해지지만 사람이 수동으로 설정 할 수도 있다.

In [31]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [32]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

### 데이터의 순서 바꾸기

In [33]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.random.shuffle(x)
x

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

### 데이터 샘플링

choice명령어를 통해 샘플링 가능

np.random.choice( a, size = None, replace = True, p = None)

a:배열이면 원래의 데이터, 정수이면 range(a)명령으로 데이터 생성

size: 정수. 샘플 숫자

replace: 불리언. True이면 한번 선택한 데이터를 다시 선택 가능(중복)

p: 배열. 각 데이터가 선택될 수 있는 확률

In [35]:
np.random.choice(x, 5, replace = False, p = None)

array([7, 8, 3, 6, 1])

In [36]:
np.random.choice(5,5,replace = True, p = [0.1,0,0.3,0.6,0])

array([3, 2, 3, 2, 3], dtype=int64)

### 난수 생성

NumPy의 random 서브 패키지에는 난수를 생성하는 다양한 명령어를 제공한다.

rand: 0 ~ 1 사이의 균일분포

randn: 가우시안 표준 정규 분포

randint: 균일 분포의 정수 난수

rand: 

* 0부터 1사이에서 균일한 확률 분포로 실수 난수를 생성한다. 숫자 인수는 생성할 난수의 크기이다. 여러개의 인수를 넣으면 해당 크기를 가진 행렬을 생성한다.

In [37]:
np.random.rand(10)

array([0.21655035, 0.13521817, 0.32414101, 0.14967487, 0.22232139,
       0.38648898, 0.90259848, 0.44994999, 0.61306346, 0.90234858])

In [38]:
np.random.rand(3,4)

array([[0.09928035, 0.96980907, 0.65314004, 0.17090959],
       [0.35815217, 0.75068614, 0.60783067, 0.32504723],
       [0.03842543, 0.63427406, 0.95894927, 0.65279032]])

randn:
* 기댓값이 0이고 표준편차가 1인 가우시안 표준 정규분포를 따르는 난수 생성

In [39]:
np.random.randn(10)

array([-1.73495876,  1.65835111,  2.29977152, -0.47113526,  1.26271548,
       -1.17051545,  1.0657892 , -0.69993739,  0.14407911,  0.3985421 ])

In [40]:
np.random.randn(3,5)

array([[ 0.02686925,  1.05583713, -0.07318342, -0.66572066, -0.04411241],
       [-0.36326702, -0.01234481,  0.04212149,  1.95929589, -0.1984257 ],
       [ 0.33053441, -1.43582841,  0.02752832,  1.12060466, -0.22403878]])

### randint:
* 인수: np.random.randint(low, high=None, size = None)


* high를 입력하지 않으면 0과 low 사이의 숫자를, high를 입력하면 low와 high 사이의 숫자를 출력한다. size는 난수의 개수이다.

In [41]:
np.random.randint(10, size = 10)

array([8, 2, 3, 0, 0, 6, 0, 6, 3, 3])

In [42]:
np.random.randint(10,20, size = 10)

array([18, 18, 18, 12, 13, 12, 10, 18, 18, 13])

In [43]:
np.random.randint(10,20, size = (3,5))

array([[18, 12, 18, 14, 13],
       [10, 14, 13, 16, 19],
       [18, 10, 18, 15, 19]])

### 정수 데이터 카운팅

이렇게 발생시킨 난수가 실수 값이라면 Histogram 등을 사용하여 분석하면 된다.
만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석 할 수 있다.

'unique' 명령은 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트 출력

'return_counts' 인수를 True로 설정하면 각 값을 가진 데이터 갯수도 출력한다.


In [44]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [45]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts = True)
index


array(['a', 'b', 'c'], dtype='<U1')

In [46]:
count

array([2, 2, 1], dtype=int64)

unique 명령어는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이
나

### -10에서 10까지 100개의 구간으로 나뉜 배열 생성

In [47]:
x = np.linspace(-10,10,100)

In [48]:
x

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72